services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: .volumes/postgres
        target: /var/lib/postgresql/data
    env_file: "docker/postgres.env"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
