# Generated by Django 5.1.1 on 2024-09-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1, null=True)),
                ('race', models.CharField(max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
