# Generated by Django 5.1.1 on 2024-09-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_player_name_startinghand_cards_startinghand_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='card_discarded',
            field=models.IntegerField(default=-1),
        ),
    ]
