# Generated by Django 5.1.1 on 2024-09-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_turn_card_discarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='card_used',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
