# Generated by Django 5.1.1 on 2024-09-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_turn_card_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='slot',
            field=models.IntegerField(null=True),
        ),
    ]
