# Generated by Django 5.1.3 on 2024-11-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_turn_computational_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='computational_time',
            field=models.FloatField(default=-1.0),
        ),
    ]
